[package]
name = "aoc-2023"
version = "0.1.0"
edition = "2021"
authors.workspace = true
readme.workspace = true
repository.workspace = true
license-file.workspace = true
keywords.workspace = true
publish.workspace = true

[dependencies]
common = { version = "0.1.0", path = "../common" }